name: Astronomer CI - Deploy code

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ deploy_request ]
  workflow_dispatch: {}

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

concurrency:
  group: astro-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # -------- PUSH / MANUAL: choose by paths --------
  deploy-from-push:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2
          token: ${{ secrets.SUBMODULES_PAT }}

      # Determine what changed by comparing with previous commit
      - name: Check what files changed
        id: changes
        run: |
          echo "=== Files changed in this commit ==="
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "$CHANGED_FILES"
          
          # Check if only DAG files changed
          DAGS_CHANGED=false
          OTHER_CHANGED=false
          
          while IFS= read -r file; do
            if [[ -n "$file" ]]; then
              echo "Analyzing file: $file"
              if [[ "$file" =~ ^dags/.* ]]; then
                echo "  -> DAG file detected"
                DAGS_CHANGED=true
              elif [[ "$file" != ".gitmodules" ]]; then
                echo "  -> Non-DAG file detected"
                OTHER_CHANGED=true
              else
                echo "  -> .gitmodules file (ignored)"
              fi
            fi
          done <<< "$CHANGED_FILES"
          
          echo "DAGS_CHANGED=$DAGS_CHANGED" >> $GITHUB_OUTPUT
          echo "OTHER_CHANGED=$OTHER_CHANGED" >> $GITHUB_OUTPUT
          
          echo ""
          echo "=== DECISION LOGIC ==="
          echo "DAGs changed: $DAGS_CHANGED"
          echo "Other files changed: $OTHER_CHANGED"
          
          if [[ "$DAGS_CHANGED" == "true" && "$OTHER_CHANGED" == "false" ]]; then
            echo "DECISION: DAG-only deploy"
            echo "DEPLOY_TYPE=dags" >> $GITHUB_OUTPUT
          else
            echo "DECISION: Full image deploy"
            echo "DEPLOY_TYPE=image" >> $GITHUB_OUTPUT
          fi

      # Install Astro CLI
      - name: Install Astro CLI
        run: |
          curl -sSL install.astronomer.io | sudo bash -s
          astro version

      # Deploy based on detected changes
      - name: Deploy DAGs only
        if: steps.changes.outputs.DEPLOY_TYPE == 'dags'
        run: |
          echo "🚀 Deploying DAGs only..."
          astro deploy ${{ vars.DEPLOYMENT_ID }} --dags

      - name: Deploy full image
        if: steps.changes.outputs.DEPLOY_TYPE == 'image'
        run: |
          echo "🚀 Deploying full image and DAGs..."
          astro deploy ${{ vars.DEPLOYMENT_ID }}

  # -------- DISPATCH (from team repos): always DAG-only --------
  deploy-from-dispatch:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          token: ${{ secrets.SUBMODULES_PAT }}

      - name: Update submodules to latest
        run: |
          git submodule update --init --recursive --remote
          echo "Updated submodules to latest commits"

      # Install Astro CLI
      - name: Install Astro CLI
        run: |
          curl -sSL install.astronomer.io | sudo bash -s
          astro version

      - name: Deploy DAGs only (forced)
        run: |
          echo "🚀 Deploying DAGs only (repository dispatch)..."
          astro deploy ${{ vars.DEPLOYMENT_ID }} --dags