name: Astronomer CI - Deploy code

on:
  push:
    branches: [ main ]              # keep normal deploys on merge
  repository_dispatch:
    types: [ deploy_request ]       # allow team repos to trigger a deploy
  workflow_dispatch: {}             # manual trigger (optional)

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}  # Deployment/Workspace/Org token

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Pull submodules to the latest commits on the tracked branches (main)
      - name: Update submodules to latest
        run: git submodule update --init --recursive --remote

      # Astronomer Default Deploy Action (auto "infer": DAGs-only vs image-and-dags)
      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.9.0
        with:
          deployment-id: ${{ vars.DEPLOYMENT_ID }}