name: Astronomer CI - Deploy code

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ deploy_request ]
  workflow_dispatch: {}

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

concurrency:
  group: astro-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # ---- PUSH or MANUAL: decide by changed paths ----
  deploy-from-push:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules via PAT)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.SUBMODULES_PAT }}

      # Decide deploy type *purely* from changed paths
      - name: Decide deploy type by paths
        id: decide
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.event.before }}"
          HEAD="${{ github.sha }}"

          # When there is no 'before' (e.g. manual run / first push), use HEAD^ if it exists
          if [ -z "$BASE" ] || [ "$BASE" = "0000000000000000000000000000000000000000" ]; then
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              BASE="$(git rev-parse HEAD^)"
            else
              # Single-commit repo fallback: treat as image-and-dags to be safe
              echo "deploy_type=image-and-dags" >> "$GITHUB_OUTPUT"
              echo "changed_paths=" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          fi

          git fetch --no-tags --prune origin +$BASE:$BASE || true
          CHANGED="$(git diff --name-only "$BASE" "$HEAD" || true)"
          echo "changed_paths<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGED" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          # If any changed path is NOT under "dags/", we need an image deploy
          if echo "$CHANGED" | grep -E '^(?!dags/).+' -q; then
            echo "deploy_type=image-and-dags" >> "$GITHUB_OUTPUT"
          # If there are changes and they are ALL under "dags/", do DAG-only
          elif [ -n "$CHANGED" ]; then
            echo "deploy_type=dags-only" >> "$GITHUB_OUTPUT"
          else
            # No changes detected (rare) -> image-and-dags to be conservative
            echo "deploy_type=image-and-dags" >> "$GITHUB_OUTPUT"
          fi

      # Optional: show what the step saw (handy for debugging)
      - name: Show changed files
        run: |
          echo "Deploy type: ${{ steps.decide.outputs.deploy_type }}"
          echo "Changed paths:"
          echo "${{ steps.decide.outputs.changed_paths }}"

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.10.1
        with:
          deployment-id: ${{ vars.DEPLOYMENT_ID }}
          deploy-type: ${{ steps.decide.outputs.deploy_type }}

  # ---- DISPATCH (from team repos): always DAG-only after updating submodules ----
  deploy-from-dispatch:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules via PAT)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.SUBMODULES_PAT }}

      - name: Update submodules to latest
        run: git submodule update --init --recursive --remote

      - name: Deploy DAGs only (forced)
        uses: astronomer/deploy-action@v0.10.1
        with:
          deployment-id: ${{ vars.DEPLOYMENT_ID }}
          deploy-type: dags-only